#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class _Templates_cshtml
    {

public static System.Web.WebPages.HelperResult ValidationTemplate(string[] errors)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 3 "..\..\Templates.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ol class=\"val-container\">\r\n");



#line 5 "..\..\Templates.cshtml"
         foreach (var error in errors)
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <li>");



#line 7 "..\..\Templates.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, error);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 8 "..\..\Templates.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ol>\r\n");



#line 10 "..\..\Templates.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
